a = list(item_synsets.values())
for word in a:
    print(word.definition())

item_synsets = {'Club' : 'cabaret.n.01',
'Military' : 'military.n.01',
'Shorts' : 'short_pants.n.01',
'Jewelry' : 'jewelry.n.01',
'Human' : 'homo.n.02',
'Speech' : 'address.n.03',
'Door' : 'door.n.01',
'Man' : 'man.n.01',
'Sunglasses' : 'sunglasses.n.01',
'Lamp' : 'lamp.n.02',
'Performer' : 'performer.n.01',
'Crypt' : 'crypt.n.01',
'Suit' : 'suit.n.01',
'Nature' : 'nature.n.03',
'Window' : 'window.n.01',
'Smile' : 'smile.n.01',
'Sport' : 'sport.n.01',
'Pianist' : 'pianist.n.01',
'Photo' : 'photograph.n.01',
'Wheel' : 'wheel.n.01',
'Beverage' : 'beverage.n.01',
'Overcoat' : 'greatcoat.n.01',
'Computer' : 'computer.n.01',
'Crowd' : 'crowd.n.01',
'Architecture' : 'architecture.n.02',
'Art' : 'art.n.01',
'School' : 'school.n.01',
'Outdoors' : 'outdoors.n.01',
'Head' : 'head.n.01',
'Girl' : 'girl.n.01',
'Chair' : 'chair.n.01',
'Sports' : 'sport.n.01',
'Robe' : 'robe.n.01',
'Sleeve' : 'sleeve.n.01',
'Stage' : 'stage.n.03',
'Clothing' : 'clothing.n.01',
'Water' : 'water.n.01',
'Grass' : 'grass.n.01',
'Dance' : 'dance.n.01',
'Finger' : 'finger.n.01',
'Tuxedo' : 'dinner_jacket.n.01',
'Flooring' : 'floor.n.01',
'Food' : 'food.n.02',
'Cushion' : 'cushion.n.03',
'Blazer' : 'blazer.n.01',
'Wood' : 'wood.n.01', 
'Street' : 'street.n.01', 
'City' : 'city.n.01', 
'Theater': 'theater.n.01', 
'Machine': 'machine.n.01', 
'Hair':  'hair.n.01',
'Screen': 'screen.n.03',
'Restaurant': 'restaurant.n.01', 
'Dating':  'date.n.03',
'Blonde': 'blond.n.01',
'Apparel': 'apparel.n.01', 
'Pillow': 'pillow.n.01',
'Party': 'party.n.04', 
'Automobile': 'car.n.01', 
'Fashion': 'fashion.n.03', 
'Tree' : 'tree.n.01', 
'Prison': 'prison.n.01', 
'Lighting': 'lighting.n.03', 
'Transportation': 'transportation_system.n.01', 
'Plywood': 'plywood.n.01', 
'Symbol': 'symbol.n.01', 
'Portrait': 'portrait.n.02', 
'Child': 'child.n.01', 
'Clinic': 'clinic.n.01', 
'Dungeon': 'keep.n.02', 
'Path': 'path.n.04', 
'Female': 'female.n.02', 
'Jacket':'jacket.n.01', 
'Animal': 'animal.n.01', 
'Shop': 'shop.n.01', 
'Face': 'face.n.01', 
'Mammal': 'mammal.n.01', 
'Banister': 'bannister.n.02', 
'Flower': 'flower.n.01', 
'Tie': 'necktie.n.01', 
'Teen': 'adolescent.n.01',
'Glasses' : 'spectacles.n.01', 
'Shelf': 'shelf.n.01', 
'Closet': 'cupboard.n.01', 
'Glass': 'glass.n.02', 
'Hand': 'hand.n.01', 
'Footwear': 'footwear.n.01', 
'Drink': 'drink.n.01', 
'Plant': 'plant.n.01',
'Monitor': 'monitor.n.04', 
'Skin': 'skin.n.01', 
'Coat': 'coat.n.01', 
'Dress': 'dress.n.01', 
'Woman': 'woman.n.01', 
'Hat': 'hat.n.01', 
'Text': 'text.n.01', 
'Building': 'building.n.01', 
'Accessory': 'accessory.n.01', 
'People': 'people.n.01', 
'Couch': 'sofa.n.01', 
'Pottery': 'pottery.n.01', 
'Helmet': 'helmet.n.02', 
'Vegetation': 'vegetation.n.01', 
'Bed': 'bed.n.01', 
'Wine': 'wine.n.01', 
'Accessories': 'accessory.n.01', 
'Pc' : 'personal_computer.n.01',
'Gown': 'gown.n.01', 
'Display': 'display.n.06', 
'Book': 'book.n.01',
'Arm': 'arm.n.01', 
'Kid': 'child.n.01', 
'Cafeteria': 'cafeteria.n.01', 
'Vehicle': 'vehicle.n.01', 
'Driving': 'driving.n.02', 
'Lecture': 'lecture.n.01', 
'Road': 'road.n.01', 
'Ear': 'ear.n.01', 
'Person': 'person.n.01', 
'Painting': 'painting.n.01', 
'Furniture': 'furniture.n.01', 
'Halo': 'aura.n.02', 
'Cafe': 'cafe.n.01', 
'Musician': 'musician.n.01', 
'Light': 'light.n.02', 
'Audience': 'audience.n.01', 
'Car': 'car.n.01', 
'Town': 'town.n.01', 
'Jaw': 'jaw.n.01', 
'Pants': 'trouser.n.01', 
'Photography': 'photography.n.01', 
'Shoe': 'shoe.n.01', 
'Pub': 'public_house.n.01',
'Desk': 'desk.n.01', 
'Worker': 'worker.n.01', 
'Room': 'room.n.01', 
'Housing': 'housing.n.01',
'Floor': 'floor.n.01', 
'Alcohol': 'alcohol.n.01', 
'Electronics': 'electronics.n.01', 
'Vigil': 'vigil.n.02', 
'Shirt': 'shirt.n.01',
'Court': 'court.n.01', 
'Table': 'table.n.02', 
'Hug': 'hug.n.01', 
'Meal': 'meal.n.01', 
'Piano': 'piano.n.01', 
'Sitting': 'sitting.n.02', 
'Pedestrian': 'pedestrian.n.01', 
'Blossom' : 'flower.n.02'}

with open('item_synsets.pickle', 'wb') as f:
    pickle.dump(item_synsets, f)

['Drink', 'Window', 'Ear', 'Jacket', 'Dress', 'Car', 'Prison', 'Path', 'Floor', 'Alcohol', 'Accessories', 'Glasses', 'Dance', 'Wine', 'Couch', 'Footwear', 'Building', 'Handrail', 'Tie', 'Desk', 'Grass', 'Town', 'Hair', 'Cafe', 'Water', 'Blonde', 'Lamp', 'Machine', 'People', 'Road', 'Sports', 'Screen', 'Vehicle', 'Nature', 'Housing', 'Shoe', 'Flower', 'Pottery', 'Monitor', 'Overcoat', 'Light', 'Cushion', 'Audience', 'Photo', 'Animal', 'Jaw', 'Apparel', 'Kid', 'Piano', 'Shelf', 'Crypt', 'Mammal', 'Clothing', 'Text', 'Child', 'Accessory', 'Female', 'Painting', 'Arm', 'Teen', 'Shirt', 'Pants', 'Bed', 'Dating', 'Face', 'Plant', 'Gown', 'Helmet', 'Photography', 'Pc', 'Sunglasses', 'Electronics', 'Coat', 'Furniture', 'Military', 'Tree', 'Girl', 'Glass', 'Vegetation', 'Room', 'Necktie', 'Food', 'Dungeon', 'Hat', 'Club', 'Skin', 'Shorts', 'Art', 'Blazer', 'City', 'Blossom', 'Theater', 'Human', 'Meal', 'Symbol', 'Sleeve', 'Performer', 'Finger', 'Court', 'Hug', 'Beverage', 'Speech', 'Architecture', 'Table', 'Musician', 'Shop', 'Clinic', 'Driving', 'Wheel', 'Closet', 'Sport', 'Head', 'Woman', 'Lecture', 'Computer', 'Tuxedo', 'Man', 'Fashion', 'Vigil', 'Street', 'Portrait', 'Restaurant', 'Worker', 'Jewelry', 'School', 'Pedestrian', 'Wood', 'Party', 'Automobile', 'Pillow', 'Crowd', 'Robe', 'Hand', 'Door', 'Transportation', 'Chair', 'Cafeteria', 'Sitting', 'Lighting', 'Banister', 'Halo', 'Flooring', 'Display', 'Pub', 'Suit', 'Plywood', 'Smile', 'Stage', 'Outdoors', 'Person']